### ISSUE TITLE
Need correction to run on php 5.3.3

### ISSUE THREAD

**Issue by dweezil36** [Alexia/PDFEmbed#10]
thanx for your work :)
compat branch generated following error (running php 5.3.3)
PHP Parse error:  syntax error, unexpected '[' in PDFEmbed.hooks.php on line 37

code should be corrected to replace '$array =[]' by '$array=array()'

**Comment by Alexia** [comment]
I corrected the issue and the change is available for download as part of the compat branch.

Please note that PHP 5.3 and PHP 5.4 no longer receive security updates from the PHP team and both have been marked end of life for over a year now.
https://secure.php.net/eol.php
https://secure.php.net/supported-versions.php

**Comment by dweezil36** [comment]
Hi Alexia
Thanx for your quick fix
and thanx for the reminder about security updates, I'll transmit to my
system admin
regards
