### ISSUE TITLE
PHP Parse error:  syntax error

### ISSUE THREAD

**Issue by rambo44** [Alexia/PDFEmbed#7]
I am using php 5.3.3 hence is trying to use the compact branch however is getting this error

PHP Parse error:  syntax error, unexpected '[' in /var/www/html/wiki/extensions/PDFEmbed/PDFEmbed.php on line 16, referer: 

I believe this is due to the square brackets not being supported with php version below 5.4+, I am not sure why the compact branch is said to be supported for php versions below 5.4 if these are using square brackets

Thanks for your help on this

**Comment by noahm** [comment]
Fixed on the compat branch with 75b89eaa
